version: "3.7"
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - kong-net

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - kong-net
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - kong-net
    depends_on:
      - elasticsearch
  
  plus:
    build: ./plus
    ports:
      - "3000:3000"
    networks:
      - kong-net
    depends_on:
      - elasticsearch

  minus:
    build: ./minus
    ports:
      - "3001:3001"
    networks:
      - kong-net
    depends_on:
      - elasticsearch

  multiply:
    build: ./multiply
    ports:
      - "3002:3002"
    networks:
      - kong-net
    depends_on:
      - elasticsearch

  divide:
    build: ./divide
    ports:
      - "3003:3003"
    networks:
      - kong-net
    depends_on:
      - elasticsearch

networks:
  kong-net:
